### ISSUE TITLE
Misleading notification when changing file type via JekyllAdmin 

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#205] opened 2016-08-29 17:47 UTC
### Describe in one or two sentences why you're opening this issue:

Renaming a .txt file as .md file throws a misleading flash notification
### Tell us a bit about yourself
- Version of JekyllAdmin I'm using <hint: use `bundle show` to check>: 0.1.0
- Version of Jekyll I'm using <hint: use `bundle show` to check>: 3.2.1
- Operating System <e.g. OS X, Windows>: Windows 7
- Browser <e.g, Safari, Chrome>: Chrome
### Steps to reproduce

Navigate to `http://localhost:3000/admin/page/new`
create demo.txt by entering that in the breadcrumb
rename demo.txt to demo.md in the breadcrumb
### Expected

Expected demo.txt to be renamed to demo.md silently or with a success! notification
### Actual

demo.txt is successfully renamed to demo.md but with a error flash notification (couldn't update page..)
### Other details
- This could be a false alarm as the plugin is infact rightfully stating that demo.txt couldn't be updated as its no longer available.
- Its nevertheless an alarm that may cause confusion for a short while.
  Possible solution: Introduce a flash notification to handle renaming. This will return a message echoing the old filename with extn and the new filename with extn

**Comment by mertkahyaoglu** [comment] 2016-08-29 18:33
I can't reproduce this. I think it is a Windows issue. I should definitely test Jekyll Admin in my Windows machine 😕

**Comment by ashmaroli** [comment] 2016-08-30 02:52
To quote myself ,
> This could be a false alarm as the plugin is infact rightfully stating that demo.txt couldn't be updated **as its no longer available.**

but yes, definitely test on a windows machine as well.

**Comment by mertkahyaoglu** [comment] 2017-01-05 20:41
As I commented [here](https://github.com/jekyll/jekyll-admin/issues/204#issuecomment-270741477), if you create a page with .txt extension, that page will be created but won't be listed anywhere. So updating it will cause an error because API cannot find it. We should either not allow creating pages with txt extension or not add any front matter if the extension is not markdown. The first one is the simpler I think.

**Comment by ashmaroli** [comment] 2017-01-06 05:52
> We should either not allow creating pages with `.txt` extension

I think it would be better to not allow change of file extension / type via the Admin interface.

--

> or not add any front matter if the extension is not markdown

don't think that's a good idea. Even `*.html` with Front Matter is a valid JekyllPage object.

**Comment by mertkahyaoglu** [comment] 2017-02-22 10:04
Closed via #307

**Closed by mertkahyaoglu** 2017-02-22 10:04 UTC
Labels: bug, help-wanted, windows
