### ISSUE TITLE
Can't install gem from git

### ISSUE THREAD

**Issue by kyleturman** [jekyll/jekyll-admin#221] opened 2016-09-13 17:51 UTC
### Description:
I'd love to be able to install the jekyll-admin gem from a git repo (so I can fork and test with an actual jekyll instance), but when I try to in my Gemfile, the /admin screen is blank.

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using: 0.1.1
* Version of Jekyll I'm using: 3.2.1
* Operating System: OS X
* Browser: Chrome

### Steps to reproduce:
- Put jekyll-admin with the git repo in my jekyll Gemfile like so:
```ruby
group :jekyll_plugins do
    gem 'jekyll-admin', git: 'git@github.com:jekyll/jekyll-admin.git'
end
```
- Run `bundle install` (everything installs fine)
- Run `bundle exec jekyll serve`
- Navigate to `localhost:4000/admin` in browser

### I expected the following:
I would expect it to function like it would using the base rubygems version, and `/admin` would be the Jekyll Admin interface.

### But got the following, instead:
A blank screen appears on `/admin` with no HTML loaded.

### Other details:
I'm a bit of a Gem/Ruby newb, so I'm might be missing something here, but I'm assuming it's missing some sort of npm build or something? Let me know what I can do to help or if this actually something worth doing.

**Comment by benbalter** [comment] 2016-09-13 18:01
See the "Running Jekyll Admin locally" section of https://jekyll.github.io/jekyll-admin/development/. You must first run `script/build`.

**Comment by kyleturman** [comment] 2016-09-13 18:24
@benbalter I guess I'm a tad confused. I'm wanting to run it as a plugin inside an existing jekyll install. How do I run `script/build` when it's a plugin inside a jekyll install?

**Comment by benbalter** [comment] 2016-09-13 18:44
@kyleturman gotcha. The easiest way would be to clone the repo locally, run `script/build` in that directory, and set your Jekyll install to use that directory, via `path` rather than `git`. The issue is that the compiled front end is not checked into Git and must be built prior to use locally.

**Comment by kyleturman** [comment] 2016-09-13 18:47
@benbalter Aha! That makes sense. Thanks, Ben.

**Closed** 2016-09-13 18:51 UTC
