### ISSUE TITLE
Could not find the document.

### ISSUE THREAD

**Issue by caspervonb** [jekyll/jekyll-admin#184] opened 2016-08-24 21:26 UTC
When trying to edit a collection document, I get an error saying "Could not find the document".

## Versions
```console
gem list --local | grep jekyll-admin
jekyll (3.1.6)
jekyll-admin (0.1.0)
```

Listing and viewing the collection works fine.

The collection is just defined as
```yaml
collections:
  tutorials:
    output: true
```

**Comment by caspervonb** [comment] 2016-08-24 21:30
Dug around a bit more, the issue seems to be that these documents are nested within sub-folders.

e.g the folder structure looks something like this
```console
_tutorials
  javascript
  html5
  css3
```

**Comment by benbalter** [comment] 2016-08-24 22:06
Thanks @caspervonb for reporting this. Super helpful. I believe this is a duplicate of https://github.com/jekyll/jekyll-admin/issues/150, a [known issue of v0.1.0](https://github.com/jekyll/jekyll-admin/releases/tag/v0.1.0). We're working on supporting subfolders, but wanted to get a version out into the wild that at least worked in the root first.

Please let us know if you think the issue is different than #150.

**Closed by benbalter** 2016-08-24 22:06 UTC

**Comment by caspervonb** [comment] 2016-08-24 22:29
@benbalter did not see that issue, seems to be a duplicate yes.
