### ISSUE TITLE
Find posts in subfolders

### ISSUE THREAD

**Issue by djcaesar9114** [jekyll/jekyll-admin#223] opened 2016-09-17 17:56 UTC
### Description:

The post editor can't fetch posts in subfolders of `_posts` directory.

### Tell us a bit about yourself:

* jekyll (3.1.6)
* jekyll-admin (0.1.1)
* Operating System <e.g. OS X, Windows>: Ubuntu 16.04
* Browser <e.g, Safari, Chrome>: Firefox

### Steps to reproduce:

Create subfolders inside the `_posts` folder, and put posts inside it.

### I expected the following:

I expected Jekyll admin to find these posts...

### But got the following, instead:

...but it can only find the titles, and when I click on the title, I get a page "Could not find the document.", with a red toast on the bottom right saying "Fetch Error
Could not fetch the doc"

**Comment by mertkahyaoglu** [comment] 2016-09-17 22:52
Duplicate of #150, #163.

**Closed** 2016-09-17 22:52 UTC
