### ISSUE TITLE
Loosen branch protection to merge clean PRs easily

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#197] opened 2016-08-27 03:18 UTC
### Description:

> **Currently, contributors will have to continuously rebase their PR to upstream/master to avoid merge commit showing up in their branch while updating that branch to the latest.**

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>: ***0.1.0***
* Version of Jekyll I'm using <HINT: use `bundle show` to check>: ***3.2.1***
* Operating System <e.g. OS X, Windows>: ***Windows***
* Browser <e.g, Safari, Chrome>: ***Chrome***

### Steps to reproduce:

- Checkout a new fork from `upstream master` with `git checkout master && git checkout -b decoy`
- Submit a simple PR after pulling upstream master to that branch. ( # -> travis: green, status: green ) to be merged to `decoy`
- Have another PR ( with changes to an entirely different file ) merged to `decoy` :grin: 

### I expected the following:

My PR to be totally green since the commits included do not cause any conflicts with destination branch `decoy`. 
(i.e. if a git rebase is called, it would exit without a pause in between)

### But got the following, instead:

- But my PR is actually part green, ( travis: green, conflicts: none ) and part grey ( outdated ).
- Clicking 'Update Branch'  adds a merge commit to the PR.

### Other details:

Removing the merge commit can only be done by rebasing to `upstream/decoy` locally follwed by a force push to `origin PR-branch` for each and every PR. :sweat:

**Comment by benbalter** [comment] 2016-08-29 19:16
I'm fine with merge commits both in feature branches and in master. Rebasing is hard concept for new users, and given a tradeoff between making Jekyll Admin easy to contribute to, and having a pristine commit history, I'd prefer to make it easier to contribute to. Since the commit history already has merge commits in it, I'm not sure much is gained by changing the practice now.

@ashmaroli you're welcome to rebase your commits. The fact that automatic merge button is disabled is an intended behavior, as tests could have been added to `master` that your branch would fail, and even if they could be merged automatically, those tests have not yet been run against your feature branch.

**Comment by ashmaroli** [comment] 2016-08-30 02:48
> and even if they could be merged automatically, those tests have not yet been run against your feature branch.

Is not that what CI is all about, when it automatically builds a new whole based on my branch, for every PR and runs tests as defined within the repo?

**Comment by mertkahyaoglu** [comment] 2016-10-30 19:07
I prefer branch protection as well. I think we can close this now.

**Closed by mertkahyaoglu** 2016-10-30 19:07 UTC
Labels: github
