### ISSUE TITLE
`baseurl` not applied to preview links in Jekyll Admin

### ISSUE THREAD

**Issue by mmistakes** [jekyll/jekyll-admin#164] opened 2016-08-22 01:11 UTC
When using `baseurl` in `_config.yml` the preview links in Jekyll Admin don't seem to apply it to the path causing 404's.

### Steps to reproduce:

1. `jekyll new admin-test`
2. Add `gem 'jekyll-admin', group: :jekyll_plugins` to Gemfile
3. `bundle install`
4. Add `baseurl: "/blog"` to _config.yml
5. `bundle exec jekyll serve`
6. Open `http://localhost:4000/admin`, click Posts, and then preview a post (clicking eye icon) or clicking the View button.

### Expected:

`http://localhost:4000/blog/<post-url>/` instead of `http://localhost:4000/<post-url>/`. This applies to pages as well.

**Comment by mertkahyaoglu** [comment] 2016-08-22 06:47
@benbalter Should we add the `baseurl` prefix to the `url` in the front end if it is present in the `_.config.yml` or should the server handle that and convert all of the `url`s accordingly?

**Comment by benbalter** [comment] 2016-08-22 14:05
Ohhh Jekyll. While you an I would call `url` something that starts with `http`, the problem is that `url` in Jekyll parlance is actually the HTML path to the site's base url (with `path` being the path on disk), both coming from `to_liquid`, and matching Jekyll's internal data structure prior to that.

I'm going to suggest adding an `html_url` (or `http_url`) field (or something more creatively named), which would be the full URL, with port, scheme, host, path, etc. (which could also parallel the `api_url` via https://github.com/jekyll/jekyll-admin/issues/37).

**Comment by mertkahyaoglu** [comment] 2016-08-23 06:51
Thanks @mmistakes This is closed via #166, #167

**Closed** 2016-08-23 06:52 UTC
